name: Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Patch package.json for compatibility
        run: |
          jq '.dependencies["next-auth"] = "^4.24.11" | .devDependencies["eslint"] = "^8.57.0"' package.json > package.tmp.json && mv package.tmp.json package.json
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Commit fixed dependencies
        run: |
          git add package.json package-lock.json
          git diff --cached --quiet || git commit -m "Fix peer dependency conflicts for deploy"
          git push || echo "No changes to push"

      - name: Build step
        run: |
          npm run build
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static
          mv .next/standalone/server.js .next/standalone/server.cjs

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "animehi-str-18"
          entrypoint: "./server.cjs"
          root: ".next/standalone"
